README.md
Small PR to fix some broken links in the README.md and add a note about the new project home. I removed the notice stating that this in not an official Google project. That shouldn't be a requirement anymore since Metacontoller is no longer hosted under the GoogleCloudPlatform organization.
=> Fixes links and adds a note about the new repository

main.go
Currently, meta controller does not explicitly set  QPS and Burst when it creates its Kube client. The default QPS is 5, this is a bottleneck on deployments where meta controller is serving multiple operators.
=> feat(perf): make QPS and Burst configurable

.github/workflows/pipeline.yaml, release.config.js
- manifests are now release asstest, available on release page
- on release, CHANGELOG.MD and manifests/metacontroller.yaml are updated
=> chore(#25): Add release assets and update manifests on release

renovate.json
Adding basic renovate configuration for updating dependencies.
I separated k8s.io to be updated in single PR, also I separated to create different PR's for major versions.
All go/docker dependencies PR's will have commit with type `fix` to trigger release build.
=> chore: Add renovate configuration

apis/metacontroller/v1alpha1/types.go, examples/bluegreen/bluegreen-controller.yaml, examples/bluegreen/sync.js, examples/catset/catset-controller.yaml, examples/crd-roles/crd-role-controller.yaml, examples/crd-roles/my-crd.yaml, examples/daemonjob/daemonjob-controller.yaml, examples/go/thing-controller.yaml, examples/indexedjob/indexedjob-controller.yaml, examples/status/noop-controller.yaml, manifests/metacontroller.yaml, test/integration/composite/composite_test.go, test/integration/decorator/decorator_test.go, test/integration/framework/crd.go, test/integration/framework/fixture.go, test/integration/framework/metacontroller.go
This PR uses [controller-gen](https://github.com/kubernetes-sigs/controller-tools/tree/master/cmd/controller-gen) in conjunction with [kubebuilder annotations](https://book.kubebuilder.io/reference/markers/crd.html) to update CRD versions to `apiextensions.k8s.io/v1`.
The CRDs can be generated using: `controller-gen crd paths=./apis/metacontroller/... output:stdout > crds.yaml`
=> chore(api): Update CRD api versions to v1

examples/service-per-pod/hooks/sync-service-per-pod.jsonnet, examples/service-per-pod/my-statefulset.yaml
In Later versions of kubernetes services with multiple ports need to have names for their ports.
This MR fixes the service-per-pod example
=> chore(examples): [#83] - Fix service-per-port sync hook

Dockerfile, go.sum, renovate.json
Temporary pin fixed dependency in docker file. Need to discuss better approach in future.
=> fix(security): Update vunerable openssl packages  CVE-2020-1971

controller/composite/controller.go, controller/composite/metacontroller.go, controller/decorator/controller.go, controller/decorator/metacontroller.go, docs/src/guide/install.md, main.go, server/server.go, test/integration/framework/main.go
This enables users to control how many webhook requests get processed in parallel.
=> feat(perf): Add a flag to configure the number of workers to run

.github/workflows/release-pipeline.yaml
Tested on https://github.com/grzesuav/metacontroller/runs/1736882334?check_suite_focus=true
=> fix(docker): Disable `latest` tag for distroless variants

release.config.js
Recently it break because of
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/
=> fix(release): #197 - Change release message to trigger CI pipeline

controller/composite/controller_revision.go, controller/composite/rolling_update.go, controller/decorator/controller.go, dynamic/object/status.go, third_party/kubernetes/unstructured.go
In this PR I removed `third_party/kubernetes` code and replace with calls to `unstructured`
=> refactor: Switch code usage to external libraries (unstructured)

docs/src/contrib/build.md, docs/src/guide/install.md
The documentation found at https://metacontroller.app/ contains raw variables which are not properly interpolated with actual values. Examples can be found in the [installation](https://metacontroller.github.io/metacontroller/guide/install.html#install-metacontroller) and [build](https://metacontroller.github.io/metacontroller/contrib/build.html#building) sections.
Looking at the capabilities of mdbook, there does not seem to be a well supported plugin for working with variables. I therefore decided to simply hardcode the actual values directly in the documentation source.
=> docs: Fix invalid URLs in documentation

test/integration/framework/main.go
The integration tests job in the CI fails occasionally and needs to be manually restarted.
After enabling more verbose logging, the error message that bubbles up seems to be [the server could not find the requested resource](https://github.com/fpetkovski/metacontroller/runs/2359962622?check_suite_focus=true#step:3:766). This error occurs when we try to create the metacontroller namespace before we run the integration test.
I assume what is happening is the apiserver is not fully initialized at this point and some kubernetes resources are not yet installed. To resolve the problem I changed the polling logic to use `kubectl get namespace` instead of `kubectl version`. This makes sure the namespace resource is available in the API before we move onward with the test.
Resolves …
=> test: Fix flakiness in integration tests

.github/workflows/documentation.yaml
To use https://github.com/Michael-F-Bryan/mdbook-docker-image as it has
all plugins for image generations
=> docs(pages): Switch docker image used to generation

pkg/controller/common/common.go, pkg/server/server.go
The current metacontrollers use a plain controller-runtime client when talking to the API server.
As a result, each read and list action goes directly to the server instead of using a cache.
This commmit initializes the client to be the same as the one from the controller manager.
In this way, reading actions will always be backed by a cache, while write actions
will be executed directly against the API server.
Signed-off-by: fpetkovski <filip.petkovsky@gmail.com>
=> perf(k8sClient): use a cache-based version of k8s client

docs/src/guide/create.md
The CRD example from the guide is missing the subresources status entry and without it the controller won't work, error is below.
```
metacontroller.go:126] "Ignoring CompositeController" name="hello-controller" reason="subresource 'Status' not enabled" groupVersionKind="example.com/v1, Kind=HelloWorld"
```
Ref https://stackoverflow.com/questions/56427423/metacontroller-how-to-stop-calls-to-sync-hooks-and-resource-generation/
=> chore(examples): #68 - Add subresources status to example CRD

pkg/controller/common/customize/hook.go, pkg/controller/common/customize/manager.go, pkg/controller/common/customize/manager_test.go, pkg/controller/common/finalizer/finalizer.go, pkg/controller/composite/controller.go, pkg/controller/composite/controller_revision.go, pkg/controller/composite/hooks.go, pkg/controller/decorator/controller.go, pkg/controller/decorator/hooks.go, pkg/hooks/hooks.go, pkg/hooks/hooks_test.go, pkg/hooks/webhook.go, pkg/hooks/webhook_test.go, pkg/internal/testutils/hooks.go
Up to now, for each invocation new httpClient was created. It was both
unefficient and forbids from further changes (like adding authentication
etc). This PR introduces Hooks Executor which are partof the controller.
=> perf(webhooks): #255 - Create httpClient per controller instead ad-hoc creation

examples/prometheus-monitoring/README.MD, examples/prometheus-monitoring/prometheus.yaml, go.mod, go.sum, manifests/debug/args.yaml, pkg/controller/common/common.go, pkg/controller/common/customize/cache.go, pkg/controller/common/customize/cache_test.go, pkg/controller/common/customize/manager.go, pkg/controller/common/customize/manager_test.go, pkg/controller/composite/controller.go, pkg/controller/decorator/controller.go, pkg/hooks/hooks.go, pkg/hooks/hooks_test.go, pkg/hooks/webhook.go, pkg/hooks/webhook_test.go, pkg/internal/testutils/hooks.go, pkg/metrics/http.go, pkg/metrics/http_test.go, test/integration/go.sum
1. Adding http client metrics, I needed to add caching mechanism to metrics, as user can de-register and re-register the same controller, and I cannot twice register the same metrics. 
2. Changed caching mechanism to store CustomizeHookResponses to expiring cache (previous implementation did't  clear old entries)
3. Minor fixes, like correct name of customize controller or passed actual loggers instead of `nil`
=> fix(metrics): Add http client metrics

pkg/dynamic/discovery/discovery.go
The purpose of this PR is to avoid completely failing API discovery if only a subset of resources fail to be fetched.
In my particular case, another team managing keda-operator-metrics-apiserver occasionally goes into a bad state causing an error discovery resources. If metacontroller is starting up for the first time, then it will get an error fetching resources and be blocked until the keda operator is in a good state and responds with resources during API discovery.
```{"level":"error","ts":1638640761.0517867,"msg":"Failed to fetch discovery info","error":"unable to retrieve the complete list of server APIs: external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request","stacktrace":"metacontroller/pkg/dynamic/discovery.(*ResourceMap).Start.func1\n\t/go/src/metac …
```
=> fix(discovery): Do not fail if missing a subset of resources during API discover

docs/src/guide/configuration.md
I was troubleshooting a couple things and wanted to disable prometheus metrics and came across the ability to disable it by setting the port to 0. See: https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/manager/manager.go#L199
@grzesuav @AmitKumarDas  I am thinking it might be better to default the value to 0 and have the user enable it if necessary. Thoughts?
=> docs: Add disable serving metrics info if port 0

main.go, pkg/server/server.go
The purpose of this PR is to avoid container restarts on startup when metacontroller is in a service mesh (istio, kuma, etc). If the service mesh sidecar takes longer to come up than metacontroller, then metacontroller will have container restarts. The K8s API healthcheck lets us know that the sidecar is properly communicating and the API server is healthy.
=> feat: Add K8s API communication check on startup

deploy/helm/metacontroller/templates/statefulset.yaml, deploy/helm/metacontroller/values.yaml
I have a usecase to be able to modify the metacontroller arguments when deploying it with the helm chart.
I have added the ability to add custom command line arguments to the helm chart. This way if the arguments change in the future we can keep the helm chart the way it is.
=> chore(helm): #302 - add custom arguments to the helm chart

pkg/controller/common/manage_children.go
Currently, regardless of whether a recreate (`ChildUpdateRecreate`/`ChildUpdateRollingRecreate`) or inplace update (`ChildUpdateInPlace`/`ChildUpdateRollingInPlace`) strategy is selected for updating children, the same message (`Recreate update strategy selected`) is shown in the log. Instead, they should print different messages.
=> fix: change invalid log message when InPlace update strategy is used

pkg/controller/common/customize/cache.go, pkg/controller/common/customize/manager.go, pkg/controller/common/customize/manager_test.go
=> fix(customize): #414 - Use 'UID' as cache key to avoid collisions between objects in different namespaces

.github/workflows/test_release.yaml
During pushes/PRs on my private fork the codecov action fails. This is to add a check that the repository owner is metacontroller due to accessing codecov.
=> chore(codecov): Add condition repository is metacontroller to run

docs/src/guide/configuration.md
Attempting to pass the option as suggested in the doc (with quotes) results in an error on bootup (and subsequent `CrashLoopBackOff`):
```
{"level":"info","ts":1644413896.8420408,"logger":"controller-runtime.metrics","msg":"metrics server is starting to listen","addr":"\":9999\""}
{"level":"error","ts":1644413896.8425508,"logger":"controller-runtime.metrics","msg":"metrics server failed to listen. You may want to disable the metrics server or use another port if it is due to conflicts","error":"error listening on \":9999\": listen tcp: address tcp/9999\": unknown port","stacktrace":"sigs.k8s.io/controller-runtime/pkg/metrics.NewListener\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.9.5/pkg/metrics/listener.go:48\nsigs.k8s.io/controller-runtime/pkg/manager.New\n\t/go/pkg/mod/sigs.k8s.io/ …
```
=> docs: fix how port for metrics is passed

pkg/controller/common/api/v1/common.go, pkg/controller/common/api/v1/common_test.go, pkg/controller/common/common.go, pkg/controller/common/customize/manager.go, pkg/controller/common/manage_children.go, pkg/controller/common/manage_children_test.go, pkg/controller/composite/api/v1/hooks.go, pkg/controller/composite/controller.go, pkg/controller/composite/controller_revision.go, pkg/controller/composite/hooks_test.go, pkg/controller/composite/rolling_update.go, pkg/controller/decorator/api/v1/hooks.go, pkg/controller/decorator/controller.go
Second part of extracting, this time common map object used to storing relative members.
=> refactor(common): #345 - Extract RelativeCommonMap to separate api package

deploy/helm/metacontroller/ci/pdb-value.yaml, deploy/helm/metacontroller/templates/pdb.yaml, docs/src/guide/helm-install.md
Signed-off-by: Roel van den Berg <roel.vandenberg@infosupport.com>
I have implemented a Pod Disruption Budget for the controller pods so that we can guarantee that there is allways a pod online when running in a HA setup.
=> feat(helm): implement pod disruption budget

pkg/controller/common/equality.go, pkg/controller/common/manage_children.go, pkg/controller/composite/controller.go, pkg/controller/composite/controller_revision.go, pkg/controller/composite/rolling_update.go, pkg/controller/decorator/controller.go
To allow change `reflect.DeepEqual` to semantic equality
=> refactor(equality): #155 - Extract equality as separate function

.github/workflows/test_release.yaml, deploy/helm/metacontroller/ci/command-args-values.yaml, deploy/helm/metacontroller/ci/default-values.yaml, deploy/helm/metacontroller/ci/leader-election-values.yaml, deploy/helm/metacontroller/ci/rbac-aggregation-rule-values.yaml, deploy/helm/metacontroller/ci/rbac-rules-values.yaml, deploy/helm/metacontroller/ci/security-context-values.yaml, deploy/helm/metacontroller/ci/service-values.yaml
Use dev image for helm tests to ensure latest code changes are compatible with chart.
I removed the symbolic link of `ci/default-values.yaml` to `values.yaml` to allow selecting the dev tag. Instead of a symbolic link, sed is used in the github action to replace the tag before executing helm chart testing workflow step.
=> cicd(helm): Use dev image for chart testing

manifests/production/metacontroller-crds-v1.yaml, pkg/apis/metacontroller/v1alpha1/types.go, pkg/apis/metacontroller/v1alpha1/zz_generated.deepcopy.go, pkg/hooks/webhook.go, pkg/hooks/webhook_test.go, pkg/internal/testutils/hooks/hooks.go
Adding possibility to set json deserialize mode to strict, which additionaly check for duplicated and unknown fields. Change is backward-compatibile, it defaults to 'loose'.
In addition, added few validations to CRD's, and used `testify` library.
Fixes #572
Signed-off-by: Grzegorz Głąb <grzesuav@gmail.com>
=> feat(webhooks): Select json deserialization mode of response: 'loose` (default) or 'strict'

.github/workflows/static.yaml, docs/src/api/compositecontroller.md, examples/bluegreen/test.sh, examples/catset/test.sh, examples/clusteredparent/test.sh, examples/configmappropagation/README.md, examples/configmappropagation/example-configmap.yaml, examples/configmappropagation/manifest/configmap-propagation.yaml, examples/configmappropagation/manifest/sync.py, examples/configmappropagation/test.sh, examples/crd-roles/test.sh, examples/daemonjob/test.sh, examples/globalconfigmap/test.sh, examples/indexedjob/test.sh, examples/leader-election/test.sh, examples/pprof-profiling/test.sh, examples/prometheus-monitoring/test.sh, examples/secretpropagation/test.sh, examples/service-per-pod/test.sh, manifests/production/metacontroller-crds-v1.yaml, pkg/apis/metacontroller/v1alpha1/types.go, pkg/apis/metacontroller/v1alpha1/zz_generated.deepcopy.go, pkg/controller/composite/controller.go, pkg/controller/composite/hooks.go, pkg/controller/composite/hooks_test.go, pkg/internal/testutils/hooks/hooks.go, test/integration/framework/metacontroller.go, test/integration/framework/webhook.go
fixes #695
Adds label selector to composite controller, which works the same way as in decorator controller. I decided not to add annotation selector, as using annotations for selections is against its design.
=> feat(composite controller): Add label selector to choose parent objects

docs/src/guide/create.md
When I tried guide, I can't create a CRD due to validation error.
```shell
The CustomResourceDefinition "helloworlds.example.com" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```
So, I added openAPIV3Schema.
=> docs(guide): Add openAPIV3Schema to example CRD

docs/src/contrib/build.md, docs/src/contrib/debug.md
Signed-off-by: Luke Bond <luke.n.bond@gmail.com>
In the process of making a PR for this project I found some things unclear or missing in the docs. This PR addresses the issues I found.
- It wasn't clear how to compile the binary, therefore I assumed the Docker build would compile it
- Some dependencies were needed for the build that I didn't have installed and took me a while to find
- Path location of the integration test binaries installation script at first appeared wrong but then I found it in a subdir
- The e2e tests don't require an empty cluster, as it states, but one that is already set up with metacontroller
=> docs: some clarifications to build and test docs

docs/src/guide/helm-install.md
Seems like the helm package being created is slightly different than what it once may have been:
```
@venkatamutyala ➜ /workspaces/venkatamutyala/metacontroller (master) $ helm package deploy/helm/metacontroller --destination deploy/helm
Successfully packaged chart and saved it to: deploy/helm/metacontroller-helm-v4.7.4.tgz
@venkatamutyala ➜ /workspaces/venkatamutyala/metacontroller (master) $ helm install metacontroller deploy/helm/metacontroller-v*.tgz
Error: INSTALLATION FAILED: repo deploy not found
```
Using the proposed change things work fine:
```
@venkatamutyala ➜ /workspaces/venkatamutyala/metacontroller (master) $ helm install metacontroller deploy/helm/metacontroller-helm-v*.tgz 
NAME: metacontroller
LAST DEPLOYED: Sun Feb  5 19:06:18 2023
NAMESPACE: default
STATUS: deployed …
```
=> chore(docs): correct command for helm install

test/integration/hack/setup.sh
gotestsum provides pre-compiled binaries for arm64, but the script was previously hard-coded to only download amd64 binaries. Now it will detect the correct architecture to use before downloading.
I also took this opportunity to surround an instance of `${PWD}` in quotes, so that it's safer and more consistent with the rest of the script.
Signed-off-by: Matthew Gamble <matthew.gamble@rea-group.com>
=> fix: Support testing on arm64

docs/src/guide/create.md
kubectl get pods will take -A, which indicates --all-namespaces and is not needed in this case because the command declares the namespace
=> chore(docs): `-a` is not a vaild flag for kubectl get pods

pkg/controller/composite/controller.go, pkg/controller/composite/controller_test.go, pkg/hooks/errors.go, pkg/hooks/webhook.go, pkg/hooks/webhook_test.go, pkg/internal/testutils/common/util.go, pkg/internal/testutils/hooks/hooks.go
Add a new feature to requeue item when the backend service returns the 429 HTTP code. The requeue after some seconds is based on `Reter-after` field in the response header.
Close: #533
=> Support rate limiting to handle HTTP 429

docs/src/contrib/debug.md
Found the documentation misleading when I tried to setup a local environment. I checked the dev deployment and found that the image name was incorrect on the documentation.
Herewith please find my fix for this. Thank you.
=> chore(docs): Updated local development image name

docs/src/api/hook.md, pkg/hooks/webhook_etag.go, pkg/hooks/webhook_etag_test.go
Fixes #850
Adds support for `412 (Precondition Failed)` responses from controllers when the provided `If-None-Match` header contains the `ETag`. As described in #850, this is the expected behavior of HTTP/1.1 as described in [RFC7232](https://www.rfc-editor.org/rfc/rfc7232#section-3.2).
I also took the liberty of updating the docs.
=> fix(hooks): Make ETag header RFC compliant

pkg/controller/common/customize/manager.go
The customize hook cache would reach TTL and expire; the cached item would no longer be found. The loop in find findRelatedParents would trigger the continue which would skip over all the related rules to be processed.
By replacing getCachedCustomizeHookResponse with getCustomizeHookResponse, if the cached item is not found, it would then trigger the customize hook call and update the cache. The related items would then continue to be processed.
fixes: https://github.com/metacontroller/metacontroller/issues/731
=> fix(related_resources): Call getCustomizeHookResponse instead of getCachedCustomizeHookResponse

.github/workflows/helm_release.yaml, .goreleaser.yaml, release.config.js
Helm only respects strict semver v2. That means no v prefixes.
This change removes the v prefix both from the chart and the published
OCI artifact tag.
Fixes #946
=> fix(helm): [#946] - Drop v prefix from helm chart version

go.mod, go.sum, pkg/controller/common/manage_children.go, pkg/dynamic/controllerref/controller_revision.go, pkg/dynamic/controllerref/unstructured.go, pkg/hooks/webhook_test.go, test/integration/framework/metacontroller.go, test/integration/go.mod, test/integration/go.sum
Manual fix for failing renovate PR: [fix(deps): update k8s.io/utils digest to 4693a02](https://github.com/metacontroller/metacontroller/pull/935) - (925 can be closed when this one is merged)
Also switched from the deprecated "k8s.io/utils/pointer" package to "k8s.io/utils/ptr" package.
=> fix(deps): update k8s.io/utils digest to 4693a02

deploy/helm/metacontroller/crds/metacontroller-crds-v1.yaml, docs/src/api/compositecontroller.md, docs/src/api/decoratorcontroller.md, pkg/apis/metacontroller/v1alpha1/types.go, pkg/apis/metacontroller/v1alpha1/zz_generated.deepcopy.go, pkg/controller/composite/controller.go, pkg/controller/decorator/controller.go
fixes part of #986
- introduces a field `ignoreStatusChanges` in the API of both - decorator and composite controller
- if its set to `true`, only spec changes or label/annotation changes will be honored for reconcilation.
=> feat: #986 - Ignore status changes for parent resources in dec and cc controller

pkg/controller/composite/controller.go, pkg/controller/decorator/controller.go
fixes part of https://github.com/metacontroller/metacontroller/issues/986
we should also handle the case when `deletiontimestamp` is added to the parent object, metacontroller should enqueue it. Otherwise, whenever a parent object is deleted, because only timestamp is added in metadata, it will come to `updateParentObject()` method which will ignore it because there has been no change in the generation, labels or annotations.
=> fix: allow update enqueue for parent resources being deleted when ignoreStatusChanges is being set to true

examples/bluegreen/my-bluegreen.yaml, examples/catset/my-catset.yaml, examples/clusteredparent/manifest/cluster-parent.yaml, examples/clusteredparent/manifest/sync.py, examples/clusteredparent/sync.py, examples/configmappropagation/manifest/configmap-propagation.yaml, examples/configmappropagation/manifest/sync.py, examples/crd-roles/manifest/crd-role-controller.yaml, examples/crd-roles/manifest/sync.py, examples/daemonjob/manifest/daemonjob-controller.yaml, examples/daemonjob/manifest/sync.py, examples/globalconfigmap/manifest/globalconfigmap.yaml, examples/globalconfigmap/manifest/sync.py, examples/indexedjob/manifest/indexedjob-controller.yaml, examples/indexedjob/manifest/sync.py, examples/kind-load-images.sh, examples/secretpropagation/manifest/secret-propagation.yaml, examples/secretpropagation/manifest/sync.py, examples/secretpropagation/secret-propagation.yaml, examples/service-per-pod/my-statefulset.yaml
Updated python version as well as python example code to use python 3.11.
Updated nginx image to use version 1.26.2.
Converted python2 code to python3.
Added examples/kind-load-images.sh utility script that will load the container images used in the examples to a running kind cluster.
=> chore(examples): update python examples to use python 3.11
