metacontroller/metacontroller

.github/PULL_REQUEST_TEMPLATE.md
.github/semantic.yml
CONTRIBUTING.md

Already installed semantic pull request app

chore(release): Set up semantic commits

---

.github/workflows/pipeline.yaml
.github/workflows/release-pipeline.yaml
release.config.js

PLEASE DO NOT MERGE YET
Things which need to be changed/setup
1. change repo name in relese-docker workflow from `grzesuav/metacontroller` to `metacontroller/metacontroller`
2. Set up NEXUS_USERNAME and NEXUS_PASSWORD (as access token, not actual password) secrets
3. Set up PAT (personal access token) secret
To check :
* release job passed - https://github.com/grzesuav/metacontroller/actions/runs/125241273 and triggered a 0.5.0 release (when I merged fake commit)
* on tag 0.5.0 - docker push action passed - https://github.com/grzesuav/metacontroller/actions/runs/125244351 and triggered this docker  image  - https://hub.docker.com/repository/docker/grzesuav/metacontroller

chore(release): #8 - Set-up semantic-release

---

README.md

Signed-off-by: AmitKumarDas <amit.das@mayadata.io>

fix(readme): update immediate action items

---

README.md

chore(badges): Add several informational badges

---

.dockerignore
.github/workflows/pipeline.yaml
Dockerfile.test
Makefile
hack/get-kube-binaries.sh
test/integration/framework/apiserver.go
test/integration/framework/main.go

Initial idea, not sure about dockerfile name

chore(tests): #13 - Prepare dockerfile running unit and integration tests

---

README.md

Adding badge with grade and link to report  - https://goreportcard.com/report/github.com/metacontroller/metacontroller

chore(readme): Add gocard badge

---

renovate.json

chore(renovate): Remove pin-digest and adjust commit body

---

examples/bluegreen/README.md
examples/catset/README.md
examples/clusteredparent/README.md
examples/configmappropagation/README.md
examples/crd-roles/README.md
examples/daemonjob/README.md
examples/globalconfigmap/README.md
examples/indexedjob/README.md
examples/secretpropagation/README.md
examples/service-per-pod/README.md
examples/status/README.md

Redirect to new home (GoogleCloudPlatform -> metacontroller)

chore(docs): Update example readme link to new github site

---

docs/src/guide/create.md

chore(examples): Update "Create a Controller" to use python3

---

renovate.json

- test prefix for test dependencies
- enable postUpdate go related commands

chore(renovate): Adjust renovate configurations

---

controller/common/common.go
controller/composite/controller.go
controller/composite/metacontroller.go
controller/decorator/controller.go
controller/decorator/metacontroller.go
main.go
options/configuration.go
server/server.go
test/integration/framework/main.go

Should be review after event PR will be merged to make it eaiser

refactor: Extract common runtime context for passing metacontroller options

---

controller/common/common.go
controller/composite/controller.go
controller/composite/metacontroller.go
controller/decorator/controller.go
controller/decorator/metacontroller.go
events/events.go

fix(events): Emit events for controller sync errors

---

.github/workflows/static.yaml

Previous one does not allow to comment on PR's from actions

chore(linters): Change event used to trigger linter actions

---

docs/src/guide/best-practices.md

docs(pages): #239 - Document relationships between objects

---

.github/workflows/test_release.yaml
test/integration/go.mod
test/integration/go.sum

chore: Fix github workflow

---

pkg/controller/common/customize/hook.go
pkg/controller/common/customize/manager_test.go
pkg/controller/composite/hooks.go
pkg/controller/decorator/hooks.go
pkg/hooks/hooks.go
pkg/hooks/webhook.go

chore: #199 - Log hook type in logs

---

.github/workflows/static.yaml
.golangci.yaml
pkg/apis/metacontroller/v1alpha1/roundtrip_test.go
pkg/apis/metacontroller/v1alpha1/types.go
pkg/controller/common/customize/manager.go
pkg/controller/common/customize/manager_test.go
pkg/controller/composite/controller.go
pkg/controller/composite/rolling_update.go
pkg/controller/decorator/controller.go
pkg/hooks/webhook.go

chore: Adjust linters

---

go.mod
go.sum
pkg/controller/common/common.go
pkg/controller/common/common_test.go
pkg/controller/common/customize/manager.go
pkg/controller/common/manage_children.go
pkg/controller/composite/controller.go
pkg/controller/composite/controller_revision.go
pkg/controller/composite/hooks.go
pkg/controller/composite/hooks_test.go
pkg/controller/composite/rolling_update.go
pkg/controller/decorator/controller.go
pkg/controller/decorator/hooks.go
test/integration/go.sum

Adding more typing to internal collections to avoid errors and for readability

refactor(ChildMap): Add typing to ChildMap

---

main.go

Fixes https://github.com/metacontroller/metacontroller/issues/289

fix(main): Fix waiting on signal before exiting

---

docs/src/guide/install.md
go.mod
go.sum
main.go
pkg/options/configuration.go
pkg/server/server.go
test/integration/framework/main.go

fix(metrics): Utilize controller-runtime  metrics server

---

.github/workflows/release-pipeline.yaml

fix(docker): #351 - Add arm32 image

---

.github/workflows/release-pipeline.yaml

fix(release): Fix latest tag, to point to alpine image

---

.github/workflows/release-pipeline.yaml
deploy/helm/metacontroller/Chart.yaml

Example artifact on my fork - https://github.com/grzesuav/metacontroller/pkgs/container/metacontroller-helm

chore: Add helm chart to repo

---

README.md
deploy/helm/metacontroller/Chart.yaml
docs/src/guide/helm-install.md
docs/src/guide/install.md

Cleaning up readme, I believe that for remaining issues - they should be reopened here as bugs/feature resquests.

chore(readme): Update readme

---

.github/config/chart-testing/etc/chart_schema.yaml
.github/config/chart-testing/etc/lintconf.yaml
.github/config/kind-matrix-config.json
.github/workflows/test_release.yaml
deploy/helm/metacontroller/ci/default-values.yaml
deploy/helm/metacontroller/ci/rbac-aggregation-rule-values.yaml
deploy/helm/metacontroller/ci/rbac-rules-values.yaml
deploy/helm/metacontroller/templates/clusterrole.yaml
deploy/helm/metacontroller/values.yaml
docs/src/guide/helm-install.md

#471 Is requesting to allow value overrides for `ClusterRole` rules. I also have a use case using aggregationRule so I have added them together in this PR.

feat(helm): #471 - Expose rules and aggregateRule in ClusterRole

---

deploy/helm/metacontroller/templates/statefulset.yaml

fix(helm): Change helm field zapLogLevel to zap.logLevel

---

examples/catset/my-catset.yaml
pkg/dynamic/apply/apply.go

fix(dynamic apply): Add `path` key as candidate to list merging

---

Dockerfile
Dockerfile.debug
deploy/helm/metacontroller/ci/command-args-values.yaml
deploy/helm/metacontroller/ci/debug-values.yaml
deploy/helm/metacontroller/ci/leader-election-values.yaml
deploy/helm/metacontroller/ci/rbac-aggregation-rule-values.yaml
deploy/helm/metacontroller/ci/security-context-values.yaml
deploy/helm/metacontroller/values.yaml

Updating alpine Dockerfile to run as nonroot user. Following the same uid/name/group as distroless images (see https://github.com/GoogleContainerTools/distroless/blob/0d757ece34cdc83a2148cea6c697e262c333cb84/base/base.bzl#L8)

feat(Dockerfile): Run apline images as nonroot user

---

examples/prometheus-monitoring/test.sh

Wait for CRD creation to avoid race condition in prometheus test

cicd: fix prometheus test flakiness

---

go.mod
go.sum
pkg/controller/composite/hooks.go
test/integration/go.mod
test/integration/go.sum

plus remove unintended package dependency of errors

fix(deps): Update k8s.io/utils to v0.0.0-20220812165043-ad590609e2e5

---

CHANGELOG.md
deploy/helm/metacontroller/Chart.yaml
manifests/production/metacontroller.yaml
release.config.js

Please, go through these steps before you submit a PR.
1. This repository follows semantic versioning convention, therefore each PR title/commit message must follow convention: `<type>(<scope>): [#issue_number] - <subject>`. 
`type` is defining if release will be triggering after merging submitted changes, details in [CONTRIBUTING.md](../CONTRIBUTING.md). `#issue_number` is optional, when commit resolves any github issue.
Most common types are:
* `feat` - for new features
* `fix` - for bug fixes or improvements
* `chore` - changes not related to code
IMPORTANT: Please review the [CONTRIBUTING.md](../CONTRIBUTING.md) file for detailed contributing guidelines.
**PLEASE REMOVE THIS TEMPLATE BEFORE SUBMITTING**

chore: Simplify release

---

.github/workflows/test_release.yaml

fix(helm): Publish helm chart on release

---

pkg/dynamic/apply/apply.go

Fixes #650
Signed-off-by: Grzegorz Głąb <grzesuav@gmail.com>

fix(dynamic apply): Add 'mountPath' as known merge keys

---

CHANGELOG.md
deploy/helm/metacontroller/Chart.yaml
manifests/production/metacontroller.yaml

This reverts commit b0d00520249a1aafb56513f4b5b5e04973324d76.

Revert "chore(release): 4.7.3"

---

.goreleaser.yaml

Signed-off-by: Dr. Carsten Leue <carsten.leue@de.ibm.com>

feat: Add 390x support

---

CHANGELOG.md
deploy/helm/metacontroller/Chart.yaml
manifests/production/metacontroller.yaml

This reverts commit c54c27e549bc35827ccf4d451b4266da0ad5a298.

Revert "chore(release): 4.10.6"

---

.github/workflows/test_release.yaml

test(helm): #713 Always run helm chart testing

---

pkg/controller/composite/controller.go
pkg/controller/composite/controller_revision.go
pkg/controller/composite/hooks.go
pkg/internal/testutils/hooks/hooks.go

fix(hooks): #702 Handle missing sync hook scenario

---

docs/src/guide/helm-install.md

updated example command using helm oci since it is not v-prefixed anymore.

chore(docs): Update helm-install.md

---

deploy/helm/metacontroller/crds/metacontroller-crds-v1.yaml
manifests/production/metacontroller-crds-v1.yaml

Fixes https://github.com/metacontroller/metacontroller/issues/1089

fix(crds): regenerated crds to include missing field ignoreStatusChanges

---

Dockerfile.debug
Dockerfile.distroless
Dockerfile.distroless-debug
go.mod
test/integration/go.mod

fix(docker,security): Update distroless bage image
